---
urls_certificados: []

dias_alerta: 90
dias_reenvio_alerta: 10
modo_sin_smtp: true

pivot_state_dir: /home/ec2-user/cert_monitor/state
pivot_output_dir: /home/ec2-user/cert_monitor/output
estado_filename: estado_notificacion.json
csv_filename: certs_report.csv

smtp_host: ""
smtp_port: 25
smtp_use_starttls: false
smtp_username: ""
smtp_password: ""
correo_from: ""
correo_to: []

ambiente_nombre: "CERT MONITOR"
dt_fmt: "%Y-%m-%d %H:%M:%S"
